# Generated by Django 4.2.4 on 2023-08-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
                ('category', models.CharField(choices=[('Novels', 'Novels'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Young Adult', 'Young Adult'), ('Thriller', 'Thriller'), ('Self-Help & Personal Growth', 'Self-Help & Personal Growth')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.FloatField(default=29.99)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
