# Generated by Django 4.2.4 on 2023-08-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
