# Generated by Django 4.2.4 on 2023-08-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='Country, City, Street', max_length=1000),
        ),
    ]
