# Generated by Django 4.2.4 on 2023-08-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_phone_alter_order_shipping_address_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='firstname', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='lastname', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.FloatField(default=29.99),
        ),
    ]
