# Generated by Django 4.2.4 on 2023-08-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_name_user_username_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
    ]
