# Generated by Django 4.2.4 on 2023-08-31 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
